
//A:[{display:"安庆",data:"177"},{display:"鞍山",data:"178"},
/*
var datas = mydata.data;
for(key in datas){
	var arr = datas[key];
	var len = arr.length;
	var str_arr = [];
	for (var i = 0; i < len; ++i){
		var item = arr[i];
		var str = '{display:"'+item.divisionName+'",data:"'+item.divisionId+'"}';
		str_arr[i] = str;
	};
	console.log('"'+key+'":['+str_arr.join(",")+']');
}
*/
var citys = {
"A":[{display:"阿拉善盟",data:"alashanmeng"},{display:"鞍山",data:"anshan"},{display:"安庆",data:"anqing"},{display:"安阳",data:"anyang"},{display:"安顺",data:"anshun"},{display:"安康",data:"ankang"},{display:"安吉",data:"anji"},{display:"安丘",data:"anqiu"}],
"B":[{display:"北京",data:"beijing"},{display:"保定",data:"baoding"},{display:"蚌埠",data:"bengbu"},{display:"包头",data:"baotou"},{display:"巴彦淖尔",data:"bayannaoer"},{display:"本溪",data:"benxi"},{display:"白山",data:"baishan"},{display:"白城",data:"baicheng"},{display:"亳州",data:"bozhou"},{display:"滨州",data:"binzhou"},{display:"北海",data:"beihai"},{display:"百色",data:"baise"},{display:"巴中",data:"bazhong"},{display:"毕节",data:"bijiediqu"},{display:"保山",data:"baoshan"},{display:"宝鸡",data:"baoji"},{display:"白银",data:"baiyin"},{display:"滨海",data:"binhai"},{display:"宝应",data:"baoying"}],
"C":[{display:"重庆",data:"chongqing"},{display:"成都",data:"chengdu"},{display:"长沙",data:"changsha"},{display:"常州",data:"changzhou"},{display:"长春",data:"changchun"},{display:"承德",data:"chengde"},{display:"沧州",data:"cangzhou"},{display:"长治",data:"changzhi"},{display:"赤峰",data:"chifeng"},{display:"朝阳",data:"chaoyang"},{display:"滁州",data:"chuzhou"},{display:"巢湖",data:"chaohu"},{display:"池州",data:"chizhou"},{display:"常德",data:"changde"},{display:"郴州",data:"chenzhou"},{display:"潮州",data:"chaozhou"},{display:"崇左",data:"chongzuo"},{display:"楚雄",data:"chuxiong"},{display:"昌吉",data:"changji"},{display:"从化",data:"conghua"},{display:"常熟",data:"changshu"},{display:"慈溪",data:"cixi"},{display:"长兴",data:"changxing"},{display:"昌邑",data:"changyi"},{display:"苍南",data:"cangnan"},{display:"长葛",data:"changge"},{display:"崇州",data:"chongzhou"},{display:"赤壁",data:"chibi"},{display:"淳安",data:"chunan"}],
"D":[{display:"大连",data:"dalian"},{display:"大庆",data:"daqing"},{display:"东莞",data:"dongguan"},{display:"大同",data:"datong"},{display:"丹东",data:"dandong"},{display:"东营",data:"dongying"},{display:"德州",data:"dezhou"},{display:"德阳",data:"deyang"},{display:"达州",data:"dazhou"},{display:"大理",data:"dali"},{display:"丹阳",data:"danyang"},{display:"东阳",data:"dongyang"},{display:"德清",data:"deqing"},{display:"大丰",data:"dafeng"},{display:"东台",data:"dongtai"},{display:"东港",data:"donggang"},{display:"登封",data:"dengfeng"},{display:"儋州",data:"danzhou"},{display:"都江堰",data:"dujiangyan"},{display:"大石桥",data:"dashiqiao"},{display:"大冶",data:"daye"},{display:"东兴",data:"dongxing"},{display:"调兵山",data:"diaobingshan"},{display:"灯塔",data:"dengta"},{display:"邓州",data:"dengzhou"}],
"E":[{display:"鄂尔多斯",data:"eerduosi"},{display:"鄂州",data:"ezhou"},{display:"恩施",data:"enshi"},{display:"峨眉山",data:"emeishan"},{display:"额尔古纳",data:"eerguna"}],
"F":[{display:"福州",data:"fuzhou"},{display:"佛山",data:"foshan"},{display:"抚顺",data:"fushun"},{display:"阜新",data:"fuxin"},{display:"阜阳",data:"fuyang"},{display:"抚州",data:"fuzhoufz"},{display:"防城港",data:"fangchenggang"},{display:"富阳",data:"fuyangfy"},{display:"福清",data:"fuqing"},{display:"阜宁",data:"funing"},{display:"奉化",data:"fenghua"},{display:"肥城",data:"feicheng"},{display:"凤城",data:"fengcheng"}],
"G":[{display:"广州",data:"guangzhou"},{display:"桂林",data:"guilin"},{display:"贵阳",data:"guiyang"},{display:"赣州",data:"ganzhou"},{display:"贵港",data:"guigang"},{display:"广元",data:"guangyuan"},{display:"广安",data:"guangan"},{display:"固原",data:"guyuan"},{display:"高邮",data:"gaoyou"},{display:"广饶",data:"guangrao"},{display:"巩义",data:"gongyi"},{display:"桂平",data:"guiping"},{display:"公主岭",data:"gongzhuling"},{display:"高密",data:"gaomi"},{display:"广汉",data:"guanghan"},{display:"藁城",data:"gaocheng"},{display:"高平",data:"gaoping"},{display:"高碑店",data:"gaobeidian"},{display:"个旧",data:"gejiu"},{display:"高州",data:"gaozhou"},{display:"盖州",data:"gaizhou"}],
"H":[{display:"杭州",data:"hangzhou"},{display:"合肥",data:"hefei"},{display:"海口",data:"haikou"},{display:"葫芦岛",data:"huludao"},{display:"哈尔滨",data:"haerbin"},{display:"邯郸",data:"handan"},{display:"衡水",data:"hengshui"},{display:"呼和浩特",data:"huhehaote"},{display:"呼伦贝尔",data:"hulunbeier"},{display:"鹤岗",data:"hegang"},{display:"黑河",data:"heihe"},{display:"淮安",data:"huaian"},{display:"湖州",data:"huzhou"},{display:"淮南",data:"huainan"},{display:"淮北",data:"huaibei"},{display:"黄山",data:"huangshan"},{display:"菏泽",data:"heze"},{display:"鹤壁",data:"hebi"},{display:"黄石",data:"huangshi"},{display:"黄冈",data:"huanggang"},{display:"衡阳",data:"hengyang"},{display:"怀化",data:"huaihua"},{display:"惠州",data:"huizhou"},{display:"河源",data:"heyuan"},{display:"贺州",data:"hezhou"},{display:"河池",data:"hechi"},{display:"红河",data:"honghe"},{display:"汉中",data:"hanzhong"},{display:"海东",data:"haidong"},{display:"花都",data:"huadu"},{display:"海宁",data:"haining"},{display:"惠东",data:"huidong"},{display:"鹤山",data:"heshan"},{display:"海城",data:"haicheng"},{display:"海门",data:"haimen"},{display:"华阴",data:"huayin"},{display:"海阳",data:"haiyang"},{display:"霸州",data:"hbbazhou"},{display:"侯马",data:"houma"},{display:"河津",data:"hejin"},{display:"海安",data:"haian"},{display:"霍州",data:"huozhou"},{display:"黄骅",data:"huanghua"},{display:"化州",data:"huazhou"}],
"J":[{display:"济南",data:"jinan"},{display:"焦作",data:"jiaozuo"},{display:"锦州",data:"jinzhou"},{display:"九江",data:"jiujiang"},{display:"晋城",data:"jincheng"},{display:"晋中",data:"jinzhong"},{display:"吉林",data:"jilin"},{display:"鸡西",data:"jixi"},{display:"佳木斯",data:"jiamusi"},{display:"嘉兴",data:"jiaxing"},{display:"金华",data:"jinhua"},{display:"景德镇",data:"jingdezhen"},{display:"吉安",data:"jian"},{display:"济宁",data:"jining"},{display:"济源",data:"jiyuan"},{display:"荆门",data:"jingmen"},{display:"荆州",data:"jingzhou"},{display:"江门",data:"jiangmen"},{display:"揭阳",data:"jieyang"},{display:"金昌",data:"jinchang"},{display:"酒泉",data:"jiuquan"},{display:"江阴",data:"jiangyin"},{display:"嘉峪关",data:"jiayuguan"},{display:"晋江",data:"jinjiang"},{display:"靖江",data:"jingjiang"},{display:"金坛",data:"jintan"},{display:"嘉善",data:"jiashan"},{display:"江山",data:"jiangshan"},{display:"句容",data:"jurong"},{display:"建湖",data:"jianhu"},{display:"晋州",data:"jinzhoushi"},{display:"吉首",data:"jishou"},{display:"胶州",data:"jiaozhou"},{display:"建德",data:"jiande"},{display:"简阳",data:"jianyang"},{display:"介休",data:"jiexiu"},{display:"即墨",data:"jimo"}],
"K":[{display:"昆明",data:"kunming"},{display:"开封",data:"kaifeng"},{display:"克拉玛依",data:"kelamayi"},{display:"昆山",data:"kunshan"},{display:"开平",data:"kaiping"},{display:"库尔勒",data:"kuerle"},{display:"奎屯",data:"kuitun"}],
"L":[{display:"廊坊",data:"langfang"},{display:"临汾",data:"linfen"},{display:"吕梁",data:"lvliang"},{display:"辽阳",data:"liaoyang"},{display:"辽源",data:"liaoyuan"},{display:"连云港",data:"lianyungang"},{display:"丽水",data:"lishui"},{display:"六安",data:"liuan"},{display:"龙岩",data:"longyan"},{display:"莱芜",data:"laiwu"},{display:"临沂",data:"linyi"},{display:"聊城",data:"liaocheng"},{display:"洛阳",data:"luoyang"},{display:"漯河",data:"luohe"},{display:"娄底",data:"loudi"},{display:"柳州",data:"liuzhou"},{display:"来宾",data:"laibin"},{display:"泸州",data:"luzhou"},{display:"乐山",data:"leshan"},{display:"凉山",data:"liangshan"},{display:"六盘水",data:"liupanshui"},{display:"丽江",data:"lijiang"},{display:"临沧",data:"lincang"},{display:"兰州",data:"lanzhou"},{display:"溧阳",data:"liyang"},{display:"临海",data:"linhai"},{display:"兰溪",data:"lanxi"},{display:"龙口",data:"longkou"},{display:"乐昌",data:"lechang"},{display:"莱州",data:"laizhou"},{display:"临清",data:"linqing"},{display:"临安",data:"linan"},{display:"莱阳",data:"laiyang"},{display:"陆丰",data:"lufeng"},{display:"灵宝",data:"lingbao"},{display:"冷水江",data:"lengshuijiang"},{display:"乐陵",data:"laoling"},{display:"浏阳",data:"liuyang"},{display:"龙海",data:"longhai"},{display:"醴陵",data:"liling"},{display:"莱西",data:"laixi"},{display:"廉江",data:"lianjiang"},{display:"乐平",data:"leping"},{display:"阆中",data:"langzhong"},{display:"鹿泉",data:"luquan"},{display:"利川",data:"lichuan"},{display:"老河口",data:"laohekou"},{display:"凌海",data:"linghai"}],
"M":[{display:"牡丹江",data:"mudanjiang"},{display:"马鞍山",data:"maanshan"},{display:"茂名",data:"maoming"},{display:"梅州",data:"meizhou"},{display:"绵阳",data:"mianyang"},{display:"眉山",data:"meishan"},{display:"漠河",data:"mohe"},{display:"密山",data:"mishan"},{display:"满洲里",data:"manzhouli"},{display:"梅河口",data:"meihekou"},{display:"汨罗",data:"miluo"},{display:"明光",data:"mingguang"},{display:"麻城",data:"macheng"}],
"N":[{display:"宁波",data:"ningbo"},{display:"南京",data:"nanjing"},{display:"南通",data:"nantong"},{display:"南昌",data:"nanchang"},{display:"南宁",data:"nanning"},{display:"南平",data:"nanping"},{display:"宁德",data:"ningde"},{display:"南阳",data:"nanyang"},{display:"内江",data:"neijiang"},{display:"南充",data:"nanchong"},{display:"宁海",data:"ninghai"},{display:"宁乡",data:"ningxiang"},{display:"南沙",data:"nansha"},{display:"南安",data:"nanan"}],
"Q":[{display:"青岛",data:"qingdao"},{display:"齐齐哈尔",data:"qiqihaer"},{display:"泉州",data:"quanzhou"},{display:"秦皇岛",data:"qinhuangdao"},{display:"七台河",data:"qitaihe"},{display:"衢州",data:"quzhou"},{display:"清远",data:"qingyuan"},{display:"钦州",data:"qinzhou"},{display:"黔西南",data:"qianxinan"},{display:"黔东南",data:"qiandongnan"},{display:"黔南",data:"qiannan"},{display:"曲靖",data:"qujing"},{display:"庆阳",data:"qingyang"},{display:"琼海",data:"qionghai"},{display:"迁安",data:"qianan"},{display:"青州",data:"qingzhou"},{display:"启东",data:"qidong"},{display:"潜江",data:"qianjiang"},{display:"沁阳",data:"qinyang"},{display:"邛崃",data:"qionglai"}],
"P":[{display:"盘锦",data:"panjin"},{display:"莆田",data:"putian"},{display:"萍乡",data:"pingxiang"},{display:"平顶山",data:"pingdingshan"},{display:"濮阳",data:"puyang"},{display:"攀枝花",data:"panzhihua"},{display:"普洱",data:"puer"},{display:"平凉",data:"pingliang"},{display:"邳州",data:"pizhou"},{display:"平湖",data:"pinghu"},{display:"普宁",data:"puning"},{display:"平度",data:"pingdu"},{display:"彭州",data:"pengzhou"},{display:"蓬莱",data:"penglai"}],
"R":[{display:"日照",data:"rizhao"},{display:"瑞安",data:"ruian"},{display:"仁怀",data:"renhuai"},{display:"荣成",data:"rongcheng"},{display:"乳山",data:"rushan"},{display:"如皋",data:"rugao"},{display:"汝州",data:"ruzhou"},{display:"瑞金",data:"ruijin"},{display:"瑞昌",data:"ruichang"}],
"S":[{display:"上海",data:"shanghai"},{display:"深圳",data:"shenzhen"},{display:"沈阳",data:"shenyang"},{display:"石家庄",data:"shijiazhuang"},{display:"苏州",data:"suzhou"},{display:"三亚",data:"sanya"},{display:"汕头",data:"shantou"},{display:"朔州",data:"shuozhou"},{display:"四平",data:"siping"},{display:"松原",data:"songyuan"},{display:"双鸭山",data:"shuangyashan"},{display:"绥化",data:"suihua"},{display:"宿迁",data:"suqian"},{display:"绍兴",data:"shaoxing"},{display:"宿州",data:"suzhousz"},{display:"三明",data:"sanming"},{display:"上饶",data:"shangrao"},{display:"三门峡",data:"sanmenxia"},{display:"商丘",data:"shangqiu"},{display:"十堰",data:"shiyan"},{display:"随州",data:"suizhou"},{display:"邵阳",data:"shaoyang"},{display:"韶关",data:"shaoguan"},{display:"汕尾",data:"shanwei"},{display:"遂宁",data:"suining"},{display:"商洛",data:"shangluo"},{display:"石嘴山",data:"shizuishan"},{display:"顺德",data:"shunde"},{display:"石河子",data:"shihezi"},{display:"石狮",data:"shishi"},{display:"上虞",data:"shangyu"},{display:"寿光",data:"shouguang"},{display:"嵊州",data:"shengzhou"},{display:"沭阳",data:"shuyang"},{display:"射阳",data:"sheyang"},{display:"三河",data:"sanhe"},{display:"韶山",data:"shaoshan"},{display:"沙河",data:"shahe"},{display:"四会",data:"sihui"},{display:"松滋",data:"songzi"},{display:"尚志",data:"shangzhi"},{display:"舒兰",data:"shulan"}],
"T":[{display:"天津",data:"tianjin"},{display:"太原",data:"taiyuan"},{display:"唐山",data:"tangshan"},{display:"通辽",data:"tongliao"},{display:"铁岭",data:"tieling"},{display:"通化",data:"tonghua"},{display:"泰州",data:"taizhou"},{display:"台州",data:"taizhoutz"},{display:"铜陵",data:"tongling"},{display:"泰安",data:"taian"},{display:"铜仁",data:"tongrendiqu"},{display:"铜川",data:"tongchuan"},{display:"天水",data:"tianshui"},{display:"桐乡",data:"tongxiang"},{display:"太仓",data:"taicang"},{display:"台山",data:"taishan"},{display:"泰兴",data:"taixing"},{display:"滕州",data:"tengzhou"},{display:"天门",data:"tianmen"},{display:"天长",data:"tianchang"},{display:"洮南",data:"taonan"},{display:"桐城",data:"tongcheng"}],
"W":[{display:"无锡",data:"wuxi"},{display:"武汉",data:"wuhan"},{display:"芜湖",data:"wuhu"},{display:"温州",data:"wenzhou"},{display:"乌海",data:"wuhai"},{display:"乌兰察布",data:"wulanchabu"},{display:"潍坊",data:"weifang"},{display:"威海",data:"weihai"},{display:"梧州",data:"wuzhou"},{display:"文山",data:"wenshan"},{display:"渭南",data:"weinan"},{display:"武威",data:"wuwei"},{display:"吴忠",data:"wuzhong"},{display:"乌鲁木齐",data:"wulumuqi"},{display:"万州",data:"wanzhou"},{display:"吴江",data:"wujiang"},{display:"武安",data:"wuan"},{display:"温岭",data:"wenling"},{display:"文登",data:"wendeng"},{display:"吴川",data:"wuchuan"},{display:"文昌",data:"wenchang"},{display:"武穴",data:"wuxue"}],
"Y":[{display:"烟台",data:"yantai"},{display:"扬州",data:"yangzhou"},{display:"阳泉",data:"yangquan"},{display:"运城",data:"yuncheng"},{display:"营口",data:"yingkou"},{display:"延边",data:"yanbian"},{display:"盐城",data:"yancheng"},{display:"鹰潭",data:"yingtan"},{display:"宜春",data:"yichun"},{display:"宜昌",data:"yichang"},{display:"岳阳",data:"yueyang"},{display:"益阳",data:"yiyang"},{display:"永州",data:"yongzhou"},{display:"阳江",data:"yangjiang"},{display:"云浮",data:"yunfu"},{display:"玉林",data:"yulin"},{display:"宜宾",data:"yibin"},{display:"雅安",data:"yaan"},{display:"玉溪",data:"yuxi"},{display:"延安",data:"yanan"},{display:"榆林",data:"yulinyl"},{display:"银川",data:"yinchuan"},{display:"义乌",data:"yiwu"},{display:"兖州",data:"yanzhou"},{display:"宜兴",data:"yixing"},{display:"永康",data:"yongkang"},{display:"余姚",data:"yuyao"},{display:"阳朔",data:"yangshuo"},{display:"乐清",data:"yueqing"},{display:"英德",data:"yingde"},{display:"伊川",data:"yichuan"},{display:"仪征",data:"yizheng"},{display:"偃师",data:"yanshi"},{display:"扬中",data:"yangzhong"},{display:"永城",data:"yongcheng"},{display:"永济",data:"yongji"},{display:"禹城",data:"yucheng"},{display:"禹州",data:"yuzhou"},{display:"伊宁",data:"yining"},{display:"宜城",data:"yicheng"},{display:"原平",data:"yuanping"},{display:"应城",data:"yingcheng"},{display:"宜都",data:"yidu"},{display:"沅江",data:"yuanjiang"}],
"X":[{display:"西安",data:"xian"},{display:"厦门",data:"xiamen"},{display:"新乡",data:"xinxiang"},{display:"徐州",data:"xuzhou"},{display:"邢台",data:"xingtai"},{display:"忻州",data:"xinzhou"},{display:"兴安盟",data:"xinganmeng"},{display:"锡林郭勒",data:"xilinguolemeng"},{display:"宣城",data:"xuancheng"},{display:"新余",data:"xinyu"},{display:"许昌",data:"xuchang"},{display:"信阳",data:"xinyang"},{display:"襄阳",data:"xiangyang"},{display:"孝感",data:"xiaogan"},{display:"咸宁",data:"xianning"},{display:"湘潭",data:"xiangtan"},{display:"湘西",data:"xiangxi"},{display:"西双版纳",data:"xishuangbanna"},{display:"咸阳",data:"xianyang"},{display:"西宁",data:"xining"},{display:"仙桃",data:"xiantao"},{display:"兴化",data:"xinghua"},{display:"新泰",data:"xintai"},{display:"湘阴",data:"xiangyin"},{display:"响水",data:"xiangshui"},{display:"辛集",data:"xinji"},{display:"新沂",data:"xinyi"},{display:"新郑",data:"xinzheng"},{display:"新密",data:"xinmi"},{display:"荥阳",data:"xingyang"},{display:"兴宁",data:"xingning"},{display:"新民",data:"xinmin"},{display:"项城",data:"xiangcheng"},{display:"孝义",data:"xiaoyi"},{display:"湘乡",data:"xiangxiang"},{display:"兴城",data:"xingcheng"},{display:"兴平",data:"xingping"}],
"Z":[{display:"郑州",data:"zhengzhou"},{display:"淄博",data:"zibo"},{display:"珠海",data:"zhuhai"},{display:"中山",data:"zhongshan"},{display:"张家口",data:"zhangjiakou"},{display:"镇江",data:"zhenjiang"},{display:"舟山",data:"zhoushan"},{display:"漳州",data:"zhangzhou"},{display:"枣庄",data:"zaozhuang"},{display:"周口",data:"zhoukou"},{display:"驻马店",data:"zhumadian"},{display:"株洲",data:"zhuzhou"},{display:"张家界",data:"zhangjiajie"},{display:"湛江",data:"zhanjiang"},{display:"肇庆",data:"zhaoqing"},{display:"自贡",data:"zigong"},{display:"资阳",data:"ziyang"},{display:"遵义",data:"zunyi"},{display:"张掖",data:"zhangye"},{display:"中卫",data:"zhongwei"},{display:"张家港",data:"zhangjiagang"},{display:"涿州",data:"zhuozhou"},{display:"章丘",data:"zhangqiu"},{display:"诸暨",data:"zhuji"},{display:"增城",data:"zengcheng"},{display:"枣阳",data:"zaoyang"},{display:"邹平",data:"zouping"},{display:"诸城",data:"zhucheng"},{display:"庄河",data:"zhuanghe"},{display:"招远",data:"zhaoyuan"},{display:"遵化",data:"zunhua"},{display:"钟祥",data:"zhongxiang"},{display:"周庄",data:"zhouzhuang"},{display:"枝江",data:"zhijiang"},{display:"漳浦",data:"zhangpu"},{display:"樟树",data:"zhangshu"}]
};
/*
a:8
b:19
c:29
d:25
e:5
f:13

g:21
h:44
j:37
k:7
l:48
m:13
n:14

q:20
p:14
r:9
s:42
t:22

w:22
x:44
y:37
z:36

*/
for(key in citys){
	alert(key+":"+citys[key].length);
}